language: minimal

arch:
  - amd64
  - arm64

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build . -t $DOCKER_USERNAME/coredns:$(uname -p)
  - docker push $DOCKER_USERNAME/coredns:$(uname -p)
